<?xml version="1.0" encoding="utf-8"?>
<!-- WarlockLib - Visual Studio Property Sheet -->
<!-- Import this in your project: View > Property Manager > Add Existing Property Sheet -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <!-- Add include directories -->
    <IncludePath>$(ProjectDir)Include;$(ProjectDir)Core;$(ProjectDir)Access;$(ProjectDir)Evasion;$(ProjectDir)Utils;$(ProjectDir)UI;$(IncludePath)</IncludePath>
    
    <!-- Set output directory -->
    <OutDir>$(ProjectDir)Build\$(Configuration)\</OutDir>
    <IntDir>$(ProjectDir)Build\$(Configuration)\Intermediate\</IntDir>
  </PropertyGroup>
  
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(ProjectDir)Include;$(ProjectDir)Core;$(ProjectDir)Access;$(ProjectDir)Evasion;$(ProjectDir)Utils;$(ProjectDir)UI;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>WARLOCKLIB_EXPORTS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  
  <ItemGroup />
</Project>
